function y = exFixptAffineDotProduct(a,b,offset,yLike) %#codegen


    % Copyright 2019-2023 The MathWorks, Inc.

    fm = fimath('RoundingMethod', 'Floor', ...
        'OverflowAction', 'Wrap', ...
        'ProductMode', 'SpecifyPrecision', ...
        'ProductWordLength', yLike.WordLength, ...
        'ProductFractionLength', yLike.FractionLength, ...
        'SumMode', 'SpecifyPrecision', ...
        'SumWordLength', yLike.WordLength, ...
        'SumFractionLength', yLike.FractionLength, ...
        'CastBeforeSum', true);
    y2 = setfimath( cast(offset,'like',yLike), fm);
    a2 = setfimath(a,fm);
    b2 = setfimath(b,fm);
    for i=1:numel(a)
        y2(:) = y2 + (a2(i)*b2(i));
    end
    y = removefimath(y2);
end